//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMonitoring
{
    using System;
    using System.Collections.Generic;
    
    public partial class EndPoint
    {
        public long Id { get; set; }
        public Nullable<long> ServiceId { get; set; }
        public Nullable<long> EndPointTypeId { get; set; }
        public string Ip { get; set; }
        public Nullable<int> Port { get; set; }
        public string Name { get; set; }
        public string NetworkName { get; set; }
    
        public virtual EndPointType EndPointType { get; set; }
        public virtual Service Service { get; set; }
    }
}
