//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECMonitoring.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.EndPoints = new HashSet<EndPoint>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
    
        public virtual ICollection<EndPoint> EndPoints { get; set; }
    }
}
